# Generated by Django 5.0.2 on 2024-03-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=255)),
                ('Autor', models.CharField(max_length=100)),
                ('ISBN', models.IntegerField()),
                ('Numero_paginas', models.IntegerField()),
                ('Editorial', models.CharField(max_length=290)),
                ('Fecha_publicacion', models.DateTimeField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_nota', models.CharField(max_length=100)),
                ('contenido_nota', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_modificacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo_Review', models.CharField(max_length=100)),
                ('Contenido_Review', models.TextField()),
                ('Fecha_Review', models.DateTimeField()),
            ],
        ),
    ]
