# Generated by Django 4.0.6 on 2024-03-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente')], max_length=50),
        ),
    ]
