# Generated by Django 4.0.6 on 2024-03-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Cliente', 'Cliente')], max_length=50),
        ),
    ]
