# Generated by Django 4.0.6 on 2024-03-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('nota_adicional', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
